import type { BusTrip, Event, Fixture as EventFixture } from '../services/eventsApi';
import type { FanActivity } from '../services/fanActivities';
import type { Fixture } from '../services/fixtures';
import { DEMO_COMMUNITY_IDS } from './communities';
import { DEMO_MEDIA_FILES, demoMediaUrl } from './media';
import { demoDaysFromNow, demoMinutesAgo } from './time';

export const DEMO_PRIMARY_FIXTURE: Fixture & EventFixture = {
  id: 'demo-match-next',
  provider: 'demo',
  provider_fixture_id: 'demo-fixture-next',
  kickoff_at: demoDaysFromNow(10, 17, 0),
  end_time: demoDaysFromNow(10, 19, 0),
  competition: '3F Superliga',
  round: 'Næste runde',
  venue: 'Right to Dream Park',
  venue_city: 'Farum',
  home_team: 'FC Nordsjælland',
  away_team: 'Viborg FF',
  home_logo_url: null,
  away_logo_url: null,
  created_at: demoMinutesAgo(60 * 24 * 20),
  updated_at: demoMinutesAgo(60),
  home_team_provider_id: '133890',
  away_team_provider_id: 'demo-viborg',
  home_team_id: '133890',
  away_team_id: 'demo-viborg',
  lat: 55.8164,
  lng: 12.3519,
  place_name: 'Right to Dream Park',
  geocoded_at: demoMinutesAgo(60 * 24 * 30),
  raw: null,
};

export const DEMO_SECOND_FIXTURE: Fixture & EventFixture = {
  ...DEMO_PRIMARY_FIXTURE,
  id: 'demo-match-away',
  provider_fixture_id: 'demo-fixture-away',
  kickoff_at: demoDaysFromNow(18, 19, 0),
  end_time: demoDaysFromNow(18, 21, 0),
  venue: 'Energi Viborg Arena',
  venue_city: 'Viborg',
  home_team: 'Viborg FF',
  away_team: 'FC Nordsjælland',
  home_team_provider_id: 'demo-viborg',
  away_team_provider_id: '133890',
  home_team_id: 'demo-viborg',
  away_team_id: '133890',
  lat: 56.449,
  lng: 9.402,
  place_name: 'Viborg',
};

export const DEMO_EVENT: Event = {
  id: 'demo-event-warmup',
  title: 'Fælles warm-up før kampen',
  description: 'Vi mødes ved fanbaren til en rolig warm-up, sange og kampoptakt.',
  start_at: demoDaysFromNow(10, 14, 30),
  end_at: demoDaysFromNow(10, 16, 15),
  location_name: 'Fanbaren, Farum',
  location_address: 'Farum Park 2, 3520 Farum',
  organizer_group_id: DEMO_COMMUNITY_IDS.farum,
  created_by: 'demo-user-07',
  creator_user_id: 'demo-user-07',
  organizer_type: 'community',
  organizer_id: DEMO_COMMUNITY_IDS.farum,
  created_at: demoMinutesAgo(720),
  organizer: null,
  capacity: 80,
  cover_bucket: null,
  cover_path: null,
  address_line1: 'Farum Park 2',
  postal_code: '3520',
  city: 'Farum',
  country: 'Danmark',
  address_text: 'Farum Park 2, 3520 Farum',
  lat: 55.8164,
  lng: 12.3519,
  place_name: 'Fanbaren',
  geocoded_at: demoMinutesAgo(60 * 24),
};

export const DEMO_BUS_TRIP: BusTrip = {
  id: 'demo-bus-trip-viborg',
  title: 'Fælles bustur til Viborg',
  description: 'Afgang fra Farum Station. Tur-retur, fælles warm-up og god stemning hele vejen.',
  start_at: demoDaysFromNow(18, 12, 0),
  expected_return_at: demoDaysFromNow(19, 1, 0),
  departure_place: 'Farum Station',
  departure_address: 'Jernbanevej 1, 3520 Farum',
  price_dkk: 225,
  total_seats: 52,
  seats_taken: 41,
  includes: ['Bus tur-retur', 'Fælles warm-up'],
  organizer_group_id: DEMO_COMMUNITY_IDS.away,
  fixture_id: DEMO_SECOND_FIXTURE.id,
  created_at: demoMinutesAgo(960),
  updated_at: demoMinutesAgo(120),
  organizer: null,
  fixture: {
    id: DEMO_SECOND_FIXTURE.id,
    home_team: DEMO_SECOND_FIXTURE.home_team,
    away_team: DEMO_SECOND_FIXTURE.away_team,
    kickoff_at: DEMO_SECOND_FIXTURE.kickoff_at,
    venue: DEMO_SECOND_FIXTURE.venue,
  },
};

export const DEMO_FAN_ACTIVITIES: FanActivity[] = [
  {
    id: 'demo-fan-activity-warmup',
    parent_type: 'match',
    parent_id: DEMO_PRIMARY_FIXTURE.id,
    community_id: DEMO_COMMUNITY_IDS.farum,
    created_by: 'demo-user-07',
    type: 'fanbar',
    title: 'Warm-up i fanbaren',
    body: 'Mød andre fans fra kl. 14.30. Vi varmer stemmerne op og går samlet mod tribunen.',
    starts_at: DEMO_EVENT.start_at,
    ends_at: DEMO_EVENT.end_at,
    location_name: 'Fanbaren, Farum',
    location_address: 'Farum Park 2, 3520 Farum',
    lat: 55.8164,
    lng: 12.3519,
    cover_url: demoMediaUrl(DEMO_MEDIA_FILES.warmup),
    cta_label: 'Se aktivitet',
    cta_url: null,
    registration_enabled: true,
    registration_capacity: 80,
    registration_price_dkk: 0,
    registration_payment_mode: 'free',
    registration_payment_instructions: null,
    registration_mobilepay_info: null,
    registration_summary: null,
    is_published: true,
    is_cancelled: false,
    sort_order: 1,
    created_at: demoMinutesAgo(720),
    updated_at: demoMinutesAgo(90),
    community: { id: DEMO_COMMUNITY_IDS.farum, name: 'Farum Fans', type: 'community' },
  },
  {
    id: 'demo-fan-activity-march',
    parent_type: 'match',
    parent_id: DEMO_PRIMARY_FIXTURE.id,
    community_id: DEMO_COMMUNITY_IDS.tifo,
    created_by: 'demo-user-12',
    type: 'fanmarch',
    title: 'Fælles fanmarch til stadion',
    body: 'Afgang 16.15. Flag og godt humør er meget velkomne.',
    starts_at: demoDaysFromNow(10, 16, 15),
    ends_at: demoDaysFromNow(10, 16, 40),
    location_name: 'Farum Station',
    location_address: 'Jernbanevej 1, 3520 Farum',
    lat: 55.812,
    lng: 12.374,
    cover_url: demoMediaUrl(DEMO_MEDIA_FILES.stand),
    cta_label: 'Se mødested',
    cta_url: null,
    registration_enabled: false,
    registration_capacity: null,
    registration_price_dkk: 0,
    registration_payment_mode: 'free',
    registration_payment_instructions: null,
    registration_mobilepay_info: null,
    registration_summary: null,
    is_published: true,
    is_cancelled: false,
    sort_order: 2,
    created_at: demoMinutesAgo(600),
    updated_at: demoMinutesAgo(70),
    community: { id: DEMO_COMMUNITY_IDS.tifo, name: 'Tifo & Stemning', type: 'community' },
  },
];
