-- Generated by scripts/manual-song-doc-import.js
-- Source document: Ændringer til hjemmesiden_ (3).docx
-- Inserts only songs classified as NY SANG from the docx source.
-- Existing songs are left untouched.
-- source/source_key/source_url/source_hash are intentionally left NULL so
-- future Wild Tigers sync can adopt matching unsourced rows by title.
-- is_manually_edited is set to TRUE so any adopted row remains protected
-- from blind content overwrites in the sync flow.

with input_rows (title, lyrics, melody_reference, category, sort_order) as (
values
  ('Alexander Lind', 'Pasta, Pizza, Pesto
Pasta, Pizza, Pesto
Pasta, Pizza, Pesto… spiser Lind
hey, hey, hey, hey, hey', 'Hey Benjamin Nygren', 'spillersang', 1000),
  ('Ola Solbakken', 'Åhhhh Solbakken
Ola Solbakken
jeg tror bare ikke I forstår
Han dribler som en gud
han har et sindssygt skud
Vi har Solbakken', 'åååh Schjelderup', 'spillersang', 1010),
  ('Nicklas Røjkjær', 'Den ægte Røjkjær — Nicklas Røjkjær
for han spiller på banen — Den ægte Røjkjær', 'Vi ligger nummer et', 'spillersang', 1020),
  ('Hjalte Boe', 'Boe, han er go´e
Boe! Han er go´e
Boe, han er go´e
Ja han er!', 'Hey Benjamin Nygren', 'spillersang', 1030),
  ('Jakob Busk', 'Den skal klippes
Den skal trimmes
æhhhhh
vores busk', 'Vi vil kæmpe, vi vil vinde', 'spillersang', 1040),
  ('Tobias Salquist', 'lå-lå-lå-lå-lå-lå Tobias Salquist
lå-lå-lå-lå-lå Tobias Salquist', 'Better Off Alone', 'spillersang', 1050),
  ('Runar Norheim', 'Helt deroppe fra det kolde nord med evig energi
ambitioner, kampgejst, mod — Runar ka’ vi li’
Han løber til kampen er forbi
han kæmper, det kan vi alle li’', 'Vimmersvej', 'spillersang', 1060),
  ('Baba', 'Løb fra Baba seidu, nej du kan tro nej du, ka’ du løb fra Seidu, nej, hva’ tror du selv?', 'Bakke-Snagvendt', 'spillersang', 1070),
  ('Juho', 'Ud på fløjen og det går Ju-ho Ju-ho ju-ho', 'Unz Unz', 'spillersang', 1080),
  ('Villum Berthelsen', 'åhhh Villum Berthelsen!
åhhh nu tryller han igen!', 'Born in the USA', 'spillersang', 1090),
  ('Prince Junior', 'We love you Prince, we do
We love you Prince, we do
We love you Prince, we do — oh Prince we love you!', null, 'spillersang', 1100),
  ('Diallo Sanoussi', 'Diallo, Diallo, Diallo Sanoussi', 'Kalinka', 'spillersang', 1110),
  ('Alio Souleymani', 'Ali Ali Ali Ali Ali Ali Alio, åh Alio åh Alio-o-o', 'Karma Chameleon', 'spillersang', 1120),
  ('Ibrahim Adel', 'lå-lålå-lålå-lålå-lålå
lå-lålå-lålå-lålå-lålå
Ibrahim Adel, Ibrahim Adel, Ibrahim Adel', 'FC Nordsjælland', 'spillersang', 1130),
  ('Vi er FC Nordsjælland', 'Vi er FC Nordsjælland, kæmper sammen alle mand, vi holder sammen som et hold, når drengene de spiller bold… Sjå lå lå lå lå lålå', null, 'slagsang', 150),
  ('Vi er FC Nordsjælland', 'Vi er FC Nordsjælland, kæmper sammen alle mand, vi vil synge for vor hold, når vi spiller drømmebold, selvom tiden går i stå, vil vi hade dem i blå, og stå her til evig tid, Nordsjælland det er mit liv… lå lå lålå lålå lå lå…”', 'Limbo rock', 'slagsang', 160),
  ('Vi er Farums Drenge', 'Vi er Farums drenge, vi gir aldrig op, vi rejser os i samlet flok, gennem regnog slud ka intet slå os ud, ligemeget hvad der sker så står vi altid her, lalalalalala Farums drenge 4x"', 'Nordens helte synger vi vores sang', 'slagsang', 170),
  ('Vi er FC', 'For vi er FC, FC fra Farum, og vi går til fodbold, og synger højt, vi hader Lyngby, vi hader Viborg, men vi elsker, vort Nordsjælland, lå lå lålå lå', null, 'slagsang', 180),
  ('FC aha aha', 'FC aha aha fra Farum aha aha 4x
du-du-du-du-du-du-du-du-du 4x', 'That´s the way I like it', 'slagsang', 190),
  ('Jeg vil bo på Farum Kro', 'For jeg vil bo
På Farum Kro
Mellem folk
Jeg kan li’
Gamle venner
Folk jeg kender
Jeg vil bo
På Farum Kro

Lå lå hey hey
Lå lå hey hey
Lå lå hey hey
Lå lå låååå

Gamle venner
Folk jeg kender
Jeg vil bo
På den fucking kro', 'Jeg vil bo på Vesterbro/Take me home', 'slagsang', 200),
  ('Kald os lige hvad I vil', 'Vi er Nordsjælland
Kald os lig’ hvad i vil
ååh-uuh-ååhhhh
der findes ingen klub
ingen klub der´ ligesom dig
og du betyder alt for mig!', 'Kald Det Kærlighed', 'slagsang', 210),
  ('Vi maler byen rød', 'Du hænger lidt med flaget - sy''s du alt er gået i blåt?
Ja, I kender jo turen, det går jo aldrig godt
Men glem det en sæson, jeg har et sted hvor vi kan stå
Grib din egen billet for nu ska’ vi mod stadion gå

[Omkvæd]
Vi maler byen rød og himlen gul af drømmebold.
Det blå og hvide får et ekstra stænk rosé
Så tager vi 3 point, igen-igen, ligesom i 12´
Og først når dommerens sidste fløjten runger ud, vinder vi guld!', null, 'slagsang', 220),
  ('Jeg vil la'' bolden trille', 'Jeg vil la'' bolden trille
Og la'' min trøje være rød
Indtil du har set, hvad du ville
Indtil du har scoret et mål
Jeg vil la'' bolden rulle
Og la'' min trøje være rød
Se, mit hjerte gløder på stadion
For at bolden finder vejen ind', 'Jeg vil lade lyset brænde', 'slagsang', 230)
)
insert into public.songs (
  title,
  lyrics,
  melody_reference,
  spotify_url,
  category,
  sort_order,
  source,
  source_url,
  source_key,
  source_hash,
  imported_at,
  last_synced_at,
  is_manually_edited
)
select
  i.title,
  i.lyrics,
  i.melody_reference,
  null as spotify_url,
  i.category,
  i.sort_order,
  null as source,
  null as source_url,
  null as source_key,
  null as source_hash,
  now() as imported_at,
  now() as last_synced_at,
  true as is_manually_edited
from input_rows i
where not exists (
  select 1
  from public.songs s
  where s.category = i.category
    and lower(regexp_replace(trim(s.title), '\s+', ' ', 'g')) = lower(regexp_replace(trim(i.title), '\s+', ' ', 'g'))
    and lower(regexp_replace(trim(s.lyrics), '\s+', ' ', 'g')) = lower(regexp_replace(trim(i.lyrics), '\s+', ' ', 'g'))
);
